const DEFAULT_STORAGE_NAMESPACE = 'local'
const QUEUE_STORAGE_KEY = 'queue'
const LOG_DETAIL_STORAGE_KEY = 'log_detail'
const RUNNER_STORAGE_KEY = 'runner'

export {
  DEFAULT_STORAGE_NAMESPACE,
  QUEUE_STORAGE_KEY,
  LOG_DETAIL_STORAGE_KEY,
  RUNNER_STORAGE_KEY
}
